<?php /** @var $block \Femsa\Payments\Block\Info\Success */ ?>

<div class="checkout-success">

    <?php

    if (in_array($block->getMethod(), ["femsa_ef"])):
        $data = $block->getOfflineInfo();
        if (!empty($data) && isset($data["type"]) && in_array($data["type"], ['oxxo', 'cash'])):
        ?>

        <h5><?= /* @noEscape */
            __('Instructions:'); ?></h5>
        <p><?= /* @noEscape */
            __($block->getInstructions($data["type"])); ?></p>

        <table class="data" style="margin: 20px; -webkit-margin-start: 0;">
            <tbody>
            <?php
            switch ($data["type"]):
                case "oxxo":
                case "cash":
                    ?>
                    <tr>
                        <td>
                            <strong><?= /* @noEscape */
                                __('Reference Number:'); ?></strong>
                            <span
                                class="femsa_payment_reference"><?= $block->escapeHtml($data["data"]["reference"]); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong><?= /* @noEscape */
                                __('Expires at:'); ?></strong>
                            <?= $block->escapeHtml(date("Y-m-d", (integer)$data["data"]["expires_at"])); ?>
                        </td>
                    </tr>
                    <?php
                    break;
            endswitch; ?>
            </tbody>
        </table>
        <?php endif; ?>
    <?php endif; ?>
    <p>
        <?= /* @noEscape */
        __('We\'ll email you an order confirmation with details and tracking info.') ?>
    </p>
</div>
